Update test.yml

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -147,8 +147,6 @@ jobs:
 
          
           # Add the CLANG LTO and SUSFS config
-          echo "# CONFIG_HZ_250  is not set" >> $DEFCONFIG
-          echo "CONFIG_HZ_1000=y" >> $DEFCONFIG
           echo "CONFIG_LTO=y" >> $DEFCONFIG
           echo "CONFIG_LTO_CLANG=y" >> $DEFCONFIG
           echo "CONFIG_LTO_CLANG_THIN=y" >> $DEFCONFIG
@@ -188,21 +186,12 @@ jobs:
           # Use the correct defconfig for your device
           make O=out ARCH=arm64 ${{ env.CODENAME }}_defconfig
 
-      - name: Force CONFIG_HZ=1000 with scripts/config
-        run: |
-          cd "${{ env.CONFIG }}"
-          scripts/config --file out/.config --set-val CONFIG_HZ 1000
-          scripts/config --file out/.config --enable CONFIG_HZ_1000
-          scripts/config --file out/.config --disable CONFIG_HZ_100
-          scripts/config --file out/.config --disable CONFIG_HZ_250
-          make O=out ARCH=arm64 olddefconfig
-
 
       - name: Check final .config for SUSFS and LTO
         run: |
           cd "${{ env.CONFIG }}"
           echo "== Final .config  =="
-          grep -E 'CONFIG_HZ|CONFIG_LTO|CONFIG_KSU|CONFIG_SUSFS' out/.config || echo "❌ Missing expected configs"
+          grep -E 'CONFIG_LTO|CONFIG_KSU|CONFIG_SUSFS' out/.config || echo "❌ Missing expected configs"
 
 
       - name: Build the Kernel
@@ -217,7 +206,7 @@ jobs:
         run: |
           cd "${{ env.CONFIG }}"
           echo "== Final .config  =="
-          grep -E 'CONFIG_HZ|CONFIG_LTO|CONFIG_KSU|CONFIG_SUSFS' out/.config || echo "❌ Missing expected configs"
+          grep -E 'CONFIG_LTO|CONFIG_KSU|CONFIG_SUSFS' out/.config || echo "❌ Missing expected configs"
       
       - name: Copy Images
         run: |
